ad_manager_publisher_homepage:
    pattern:  /ad-manager/publishers
    defaults: { _controller: AdManagerPublisherBundle:Publisher:index }

publisher_show:
    pattern:  /ad-manager/publisher/show/{id}
    defaults: { _controller: AdManagerPublisherBundle:Publisher:show }
