ad_manager_publisher_homepage:
    pattern:  /ad-manager/publishers
    defaults: { _controller: AdManagerPublisherBundle:Publisher:index }

publisher_show:
    pattern:  /ad-manager/publisher/show/{id}
    defaults: { _controller: AdManagerPublisherBundle:Publisher:show }

ad_manager_ad_homepage:
    pattern:  /ad-manager/ads
    defaults: { _controller: AdManagerPublisherBundle:Ad:index }
ad_show:
    pattern:  /ad-manager/ad/show/{id}
    defaults: { _controller: AdManagerPublisherBundle:Ad:show }
    
add_publisher:
    pattern:  /ad-manager/publisher/add
    defaults: { _controller: AdManagerPublisherBundle:Publisher:add }
  