ad_manager_publisher_homepage:
    pattern:  /ad-manager/publishers
    defaults: { _controller: AdManagerPublisherBundle:Publisher:index }

publisher_show:
    pattern:  /ad-manager/publisher/show/{id}
    defaults: { _controller: AdManagerPublisherBundle:Publisher:show }

add_publisher:
    pattern:  /ad-manager/publisher/add
    defaults: { _controller: AdManagerPublisherBundle:Publisher:add }
    
publisher_delete:
    pattern:  /ad-manager/publisher/delete/{id}/{confirm}
    defaults: { _controller: AdManagerPublisherBundle:Publisher:delete, confirm : 0}

publisher_edit:
    pattern:  /ad-manager/publisher/edit/{id}
    defaults: { _controller: AdManagerPublisherBundle:Publisher:edit}
    
    
ad_manager_ad_homepage:
    pattern:  /ad-manager/ads
    defaults: { _controller: AdManagerPublisherBundle:Ad:index }

ad_show:
    pattern:  /ad-manager/ad/show/{id}
    defaults: { _controller: AdManagerPublisherBundle:Ad:show }
    
add_ad:
    pattern:  /ad-manager/ad/add
    defaults: { _controller: AdManagerPublisherBundle:Ad:add }
  
ad_delete:
    pattern:  /ad-manager/ad/delete/{id}/{confirm}
    defaults: { _controller: AdManagerPublisherBundle:Ad:delete, confirm : 0 }
  
ad_edit:
    pattern:  /ad-manager/ad/edit/{id}
    defaults: { _controller: AdManagerPublisherBundle:Ad:edit }
  
ad_manager_field_homepage:
    pattern:  /ad-manager/fields
    defaults: { _controller: AdManagerPublisherBundle:Field:index }
field_show:
    pattern:  /ad-manager/field/show/{id}
    defaults: { _controller: AdManagerPublisherBundle:Field:show }
    
add_field:
    pattern:  /ad-manager/field/add
    defaults: { _controller: AdManagerPublisherBundle:Field:add }
  
field_delete:
    pattern:  /ad-manager/field/delete/{id}/{confirm}
    defaults: { _controller: AdManagerPublisherBundle:Field:delete, confirm : 0 }
  
field_edit:
    pattern:  /ad-manager/field/edit/{id}
    defaults: { _controller: AdManagerPublisherBundle:Field:edit}
  
  