parameters:
#    ad_manager_publisher.example.class: AdManager\PublisherBundle\Example

services:
#    ad_manager_publisher.example:
#        class: %ad_manager_publisher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
